# Generated by Django 5.0.6 on 2024-05-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.IntegerField(choices=[(1, '<10'), (2, '<20'), (3, '<50'), (4, '<100'), (5, '<500'), (6, '>500')])),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('business_license_code', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.city')),
            ],
        ),
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.IntegerField(choices=[(1, 'Ít hơn 10'), (2, '10 - 24'), (3, '25 - 99'), (4, '100 - 499'), (5, 'Trên 500')])),
                ('company_description', models.TextField()),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('job_type', models.IntegerField(choices=[(1, 'Toàn thời gian'), (2, 'Bán thời gian'), (3, 'Hợp đồng')])),
                ('job_level', models.IntegerField(choices=[(1, 'Thực tập sinh'), (2, 'Nhân viên'), (3, 'Trưởng nhóm'), (4, 'Quản lý'), (5, 'Giám đốc')])),
                ('salary_type', models.IntegerField(choices=[(1, 'Tối thiểu'), (2, 'Tối đa'), (3, 'Thương lượng')])),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('age_type', models.IntegerField(choices=[(1, 'Bất kỳ'), (2, 'Nhỏ hơn'), (3, 'Lớn hơn'), (4, 'Từ - đến')])),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
                ('gender_type', models.IntegerField(choices=[(1, 'Bất kỳ'), (2, 'Nam'), (3, 'Nữ')])),
                ('job_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('qualification', models.IntegerField(choices=[(1, 'Không yêu cầu'), (2, 'Tốt nghiệp THPT'), (3, 'Có chứng chỉ nghề'), (4, 'Cao đẳng'), (5, 'Đại học'), (6, 'Sau đại học')])),
                ('years_of_experience', models.IntegerField(choices=[(1, 'Chưa có kinh nghiệm'), (2, '6 tháng - 1 năm'), (3, '2 - 3 năm'), (4, '4 - 5 năm'), (5, 'Trên 5 năm')])),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_address', models.CharField(max_length=255)),
                ('posting_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Chưa xác nhận'), (2, 'Đã xác nhận'), (3, 'Hết hạn'), (4, 'Đã ẩn')])),
                ('views', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.city')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.admin')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cv', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Chưa xử lý'), (2, 'Đã duyệt'), (3, 'Đã từ chối')])),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('job_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobboard')),
            ],
        ),
        migrations.CreateModel(
            name='CareerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.career')),
                ('job_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobboard')),
            ],
        ),
    ]
