# Generated by Django 5.0.6 on 2024-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboard',
            name='salary_type',
            field=models.IntegerField(choices=[(1, 'Tối thiểu'), (2, 'Tối đa'), (3, 'Từ - đến'), (4, 'Thỏa thuận')]),
        ),
    ]
