# Generated by Django 5.0.6 on 2024-05-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
        ('employer', '0002_alter_jobboard_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.admin'),
        ),
    ]
