# Generated by Django 5.0.6 on 2024-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_jobboard_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboard',
            name='age_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='salary_from',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='salary_to',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
