# Generated by Django 5.0.6 on 2024-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_jobboard_age_from_alter_jobboard_age_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboard',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chưa xác nhận'), (2, 'Đã xác nhận'), (3, 'Bị từ chối')]),
        ),
    ]
